"""
Django settings for backendnew project.
Generated by Django 5.2.1
"""

from pathlib import Path
import os
from datetime import timedelta

# -------------------------------------------------------------
# BASE SETTINGS
# -------------------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-_dyk%yd)qf-21@%&r0wy(a!%-um=w-)0b427t9$rw&fy56e-3b'

DEBUG = True   # Turn OFF in production

ALLOWED_HOSTS = [
    'lms.thirdvizion.com',
    'www.lms.thirdvizion.com',
    'localhost',
    '127.0.0.1'
]

# HTTPS / PROXY settings
SECURE_SSL_REDIRECT = False
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SECURE = False


# -------------------------------------------------------------
# INSTALLED APPS
# -------------------------------------------------------------

INSTALLED_APPS = [
    "jazzmin",
    "cloudinary",
    "django_apscheduler",
    "cloudinary_storage",

    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",

    "api",
]

# -------------------------------------------------------------
# JAZZMIN ADMIN CONFIG
# -------------------------------------------------------------

JAZZMIN_SETTINGS = {
    "site_title": "SCOPIK Admin",
    "site_header": "SCOPIK Admin",
    "site_brand": "SCOPIK",

    "welcome_sign": "Welcome to Scopik Admin",

    "navigation_expanded": True,
    "custom_css": "css/custom_admin.css",
    "custom_js": "js/mycustom.js",
}

# -------------------------------------------------------------
# EMAIL CONFIG (Use env variables for production)
# -------------------------------------------------------------

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'yeswanth6463@gmail.com'
EMAIL_HOST_PASSWORD = 'YOUR_PASSWORD_HERE'  # ❗Replace with env var

# -------------------------------------------------------------
# MIDDLEWARE
# -------------------------------------------------------------

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",

    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = 'backendnew.urls'

# -------------------------------------------------------------
# TEMPLATES
# -------------------------------------------------------------

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backendnew.wsgi.application"

# -------------------------------------------------------------
# DATABASE
# -------------------------------------------------------------

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# -------------------------------------------------------------
# PASSWORD VALIDATION
# -------------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# -------------------------------------------------------------
# INTERNATIONALIZATION
# -------------------------------------------------------------

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# -------------------------------------------------------------
# STATIC & MEDIA FILES
# -------------------------------------------------------------
STATIC_URL = '/static/'
STATICFILES_DIRS = [ BASE_DIR / "static" ]
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"

# -------------------------------------------------------------
# CORS / CSRF
# -------------------------------------------------------------

CORS_ALLOW_ALL_ORIGINS = True

CSRF_TRUSTED_ORIGINS = [
    "https://lms.thirdvizion.com",
    "https://www.lms.thirdvizion.com",
]

# -------------------------------------------------------------
# REST FRAMEWORK / JWT
# -------------------------------------------------------------

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# -------------------------------------------------------------
# DEFAULT FIELD
# -------------------------------------------------------------

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

