# Generated by Django 5.2.1 on 2025-11-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_student_university_alter_teacher_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_video',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
